replicaCount: 1

image:
  repository: saifnuaimii/app
  tag: v1.0.0
  pullPolicy: Always

service:
  name: my-app
  type: ClusterIP
  internalPort: 8080
  externalPort: 80

usersmongodb:
  mongodbUsername: root
  mongodbPassword: root
  mongodbDatabase: users
  persistence:
    enabled: false
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  resources:
    limits:
      cpu: 500m
      memory: 756Mi
    requests:
      cpu: 50m
      memory: 256Mi

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []

app:
  env:
    config:
      source: app.properties
      name: configmap-{{ .Values.app.env.config.source }}

resources:
  limits:
    cpu: 1000m
    memory: 1500Mi
  requests:
    cpu: 50m
    memory: 256Mi


nodeSelector: {}

tolerations: []

affinity: {}