apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
    helm.sh/chart: my-app-0.1.0
    app.kubernetes.io/instance: my-app
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-app
      app.kubernetes.io/instance: my-app
  template:
    metadata:
      labels:
        app: my-app
        app.kubernetes.io/instance: my-app
    spec:
      containers:
        - name: my-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ tpl ( .Values.app.env.config.name ) .}}
          ports:
            - name: http
              containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 120
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            limits:
              cpu: 1000m
              memory: 1500Mi
            requests:
              cpu: 50m
              memory: 256Mi