apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app: my-app
    helm.sh/chart: my-app-0.1.0
    app.kubernetes.io/instance: my-app
    app.kubernetes.io/managed-by: Tiller
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: http
  selector:
    app: my-app
    app.kubernetes.io/instance: my-app
